

####################################
#              Git                 #
####################################
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/pinopisello/config-repo.git
          searchPaths: licensingservice,organizationservice
          username: native-cloud-apps
          password: 0ffended




####################################
#              Native              #
####################################
#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#          # prefix: ciccio   rende service disponibile a http://localhost:8888/ciccio/licensingservice/prod
#           native:
#              searchLocations: file:////Users/glocon/Miei/local_git/nike_repo/Spring_Microservices_in_Action/spmia-chapter3/confsvr/src/main/resources/config/licensingservice,
#                               file:////Users/glocon/Miei/local_git/nike_repo/Spring_Microservices_in_Action/spmia-chapter3/confsvr/src/main/resources/config/organizationservice
##              #searchLocations: classpath:config/,classpath:config/licensingservice
